[package]
name = "rusty_mind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chess = "3.2.0"
shakmaty-syzygy = "0.25.0"
shakmaty = "0.27.0"
rand = { version = "0.8", features = ["small_rng"] }
